1	6	6	Б	У	К	Й	Р	Ы3	БУК	0	0	vertical3	КУБ	0	2	horizontal3	БУЙ	0	0	horizontal3	БУР	2	2	vertical3	РЫК	2	4	horizontal3	БЫК	4	2	vertical

2	7	6	К	К	Л	И	У	Ш4	КЛИК	0	0	vertical4	КУЛИ	0	0	horizontal3	ЛИК	2	0	vertical5	КУЛИК	2	2	horizontal3	КУШ	6	2	vertical3	ЛУК	4	2	vertical3	ШИК	2	4	horizontal

3	6	6	В	А	А	Г	М	М4	ВАГА	0	0	vertical3	ГАМ	0	2	horizontal5	ГАММА	2	0	vertical4	МАМА	2	3	horizontal5	МАГМА	4	0	vertical3	МАГ	4	0	horizontal

4	5	6	Й	О	О	Д	Ч	К3	ЙОД	0	0	vertical4	ОЧКО	0	1	horizontal3	ОКО	3	1	vertical3	КОД	3	2	horizontal3	ДОК	5	2	vertical