# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mopchik_alphabet2-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mopchik_alphabet2-desktop
	
end

target 'Mopchik_alphabet2-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mopchik_alphabet2-mobile
  pod 'YandexMobileAds'
  pod 'YandexMobileAdsAdMobAdapters'
  pod 'YandexMobileAdsIronSourceAdapters'
  pod 'YandexMobileAdsMediation'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]']='arm64'
                # config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]']='x86_64'
            end
        end
    end
end